on: push
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - run: node --version
            - run: npm --version
            - run: npm install
            - run: npm run build
            - run: npm run test
            - run: npm run deploy

            
